### ISSUE TITLE
EL modules cannot access axioms r(a,b) 

### ISSUE THREAD

**Issue by jloe2911** [bio-ontology-research-group/mowl#93]
### Describe the bug

 EL modules cannot access axioms r(a,b) 

### How to reproduce

Using `el_dls_sizes = {gci_name: len(ds) for gci_name, ds in training_datasets.items()}`, I noticed that GCI2 is empty even though there are r(a,b) axioms in the ontology I am using

### Environment

/

**Comment by ferzcam** [comment]
Hi. Since the axioms you are trying to access are $r(a,b)$, the axioms should be in  `training_datasets["object_property_assertion"]`. Would you please check if your axioms are there? Notice that  EL methods that map axioms $r(a,b) \to \\{ a \\} \sqsubseteq \exists r. \\{b\\}$ use the loss function of GCI2 for those $r(a,b)$ axioms.

**Comment by jloe2911** [comment]
Hi, yes they are there now. Thanks!
